/// Flutter icons Bottom_bar
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottom_bar
///      fonts:
///       - asset: fonts/Bottom_bar.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Bottom_bar {
  Bottom_bar._();

  static const _kFontFam = 'Bottom_bar';
  static const String? _kFontPkg = null;

  static const IconData home_1 = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xf067, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_double = IconData(0xf560, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suitcase_rolling = IconData(0xf5c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
